name: uai_notify
description: "A new Flutter project."
publish_to: "none"
version: 2.2.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- CORE PACKAGES ---
  http: ^1.2.1
  icalendar_parser: ^2.1.0
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  intl: ^0.19.0

  # --- FITUR BARU ---
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  provider: ^6.1.2
  uuid: ^4.4.0
  flutter_linkify: ^6.0.0
  # REVISI: Package baru untuk tugas latar belakang
  workmanager: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

