name: uai_notify
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Untuk mengambil data dari URL
  http: ^1.2.1

  # Untuk parsing data kalender iCalendar (ICS)
  icalendar_parser: ^2.1.0

  # Untuk menyimpan URL ICS secara lokal
  shared_preferences: ^2.2.3

  # Untuk notifikasi lokal
  flutter_local_notifications: ^17.1.2

  # Untuk menangani timezone (penting untuk notifikasi terjadwal)
  timezone: ^0.9.3

  # Untuk format tanggal dan waktu
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
